// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sales.Data;

namespace Sales.Migrations
{
    [DbContext(typeof(SalesContext))]
    [Migration("20221202000633_OutrasEntidades")]
    partial class OutrasEntidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sales.Models.Departamentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("Sales.Models.RecordeVendas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("data");

                    b.Property<double>("quantidade");

                    b.Property<int>("status");

                    b.Property<int?>("vendedoresid");

                    b.HasKey("id");

                    b.HasIndex("vendedoresid");

                    b.ToTable("RecordeVendas");
                });

            modelBuilder.Entity("Sales.Models.Vendedores", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dataAniversario");

                    b.Property<int?>("departamentosId");

                    b.Property<string>("email");

                    b.Property<string>("nome");

                    b.Property<double>("salarioBase");

                    b.HasKey("id");

                    b.HasIndex("departamentosId");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("Sales.Models.RecordeVendas", b =>
                {
                    b.HasOne("Sales.Models.Vendedores", "vendedores")
                        .WithMany("vendas")
                        .HasForeignKey("vendedoresid");
                });

            modelBuilder.Entity("Sales.Models.Vendedores", b =>
                {
                    b.HasOne("Sales.Models.Departamentos", "departamentos")
                        .WithMany("vendedores")
                        .HasForeignKey("departamentosId");
                });
#pragma warning restore 612, 618
        }
    }
}
